# Generated by Django 2.1.4 on 2019-03-11 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bgurl', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby.Age')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('picurl', models.URLField()),
                ('tinypicurl', models.URLField()),
                ('body', models.TextField(blank=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby.Age')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby.Group')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
