# Generated by Django 2.1.4 on 2019-01-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picurl',
            field=models.URLField(),
        ),
    ]
