# Generated by Django 2.1.4 on 2019-03-01 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0002_auto_20190119_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='category',
            new_name='age',
        ),
        migrations.AddField(
            model_name='picture',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baby.Group'),
            preserve_default=False,
        ),
    ]
