# Generated by Django 2.1.4 on 2019-03-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0003_auto_20190301_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
