# Generated by Django 2.1.4 on 2019-03-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0005_picture_tinypicurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='age',
            name='created_time',
            field=models.DateTimeField(default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='created_time',
            field=models.DateTimeField(default=''),
        ),
    ]
