# Generated by Django 2.1.4 on 2019-03-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0007_auto_20190306_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
