# Generated by Django 2.1.4 on 2019-03-06 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0010_auto_20190306_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='age',
            name='created_time',
        ),
        migrations.AlterField(
            model_name='group',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
