# Generated by Django 2.1.4 on 2019-03-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0011_auto_20190306_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='age',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='group',
        ),
        migrations.DeleteModel(
            name='Age',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
