# Generated by Django 2.1.4 on 2019-03-06 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0014_auto_20190306_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='age',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='baby.Age'),
            preserve_default=False,
        ),
    ]
