# Generated by Django 2.1.4 on 2019-03-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0015_group_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='age',
        ),
    ]
