# Generated by Django 2.1.4 on 2019-03-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0018_age_group_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='age',
            name='bgurl',
            field=models.URLField(blank=True),
        ),
    ]
