# Generated by Django 2.1.4 on 2019-03-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0019_age_bgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='modified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
